# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Verification_Message.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Login import *

class Ui_MainWindow7(object):
    def open_Login_Screen(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_MainWindow2()
        self.ui.setup(self.window)
        self.window.show()
        MainWindow.close()
    def setup(self, MainWindow):
        MainWindow.setObjectName("Verification")
        MainWindow.resize(474, 209)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        qss_file = open('tiger.qss').read()
        MainWindow.setStyleSheet(qss_file)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 20, 171, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 461, 131))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(200, 80, 51, 51))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../PIX/greentick2.png"))
        self.label_3.setObjectName("label_3")
        self.goBackToLoginScreen = QtWidgets.QPushButton(self.centralwidget)
        self.goBackToLoginScreen.setGeometry(QtCore.QRect(130, 140, 181, 25))
        self.goBackToLoginScreen.setObjectName("goBackToLoginScreen")
        self.goBackToLoginScreen.clicked.connect(self.open_Login_Screen)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 474, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Thankyou For Registering "))
        self.label_2.setText(_translate("MainWindow", "A Confirmation Code has been sent to your Registered Email Address"))
        self.goBackToLoginScreen.setText(_translate("MainWindow", "Go Back to Login Screen"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow7()
    ui.setup(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
