# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'changePassword.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(500, 500))
        Form.setMaximumSize(QtCore.QSize(500, 500))
        Form.setStyleSheet("")
        self.formLayoutWidget = QtWidgets.QWidget(Form)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 130, 481, 281))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setHorizontalSpacing(0)
        self.formLayout.setVerticalSpacing(100)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.new_Pass_Lbl = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.new_Pass_Lbl.setObjectName("new_Pass_Lbl")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.new_Pass_Lbl)
        self.confirm_new_Pass_Lbl = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.confirm_new_Pass_Lbl.setObjectName("confirm_new_Pass_Lbl")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.confirm_new_Pass_Lbl)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.Login_deets = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.Login_deets.setObjectName("Login_deets")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.Login_deets)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(140, 430, 221, 31))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.changePassword = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.changePassword.sizePolicy().hasHeightForWidth())
        self.changePassword.setSizePolicy(sizePolicy)
        self.changePassword.setObjectName("changePassword")
        self.verticalLayout.addWidget(self.changePassword)
        self.Password_Mismatch = QtWidgets.QLabel(Form)
        self.Password_Mismatch.setEnabled(True)
        self.Password_Mismatch.setGeometry(QtCore.QRect(10, 30, 481, 61))
        self.Password_Mismatch.setText("")
        self.Password_Mismatch.setAlignment(QtCore.Qt.AlignCenter)
        self.Password_Mismatch.setObjectName("Password_Mismatch")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "New Password:"))
        self.label_2.setText(_translate("Form", "Confirm New Password:"))
        self.label_3.setText(_translate("Form", "Email/Phone Number :"))
        self.changePassword.setText(_translate("Form", "Change Password"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
