# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Driver_Card.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form6(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(500, 500))
        Form.setMaximumSize(QtCore.QSize(500, 500))
        Form.setStyleSheet("")
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(210, 450, 71, 31))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Submit_Details3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Submit_Details3.sizePolicy().hasHeightForWidth())
        self.Submit_Details3.setSizePolicy(sizePolicy)
        self.Submit_Details3.setObjectName("Submit_Details3")
        self.verticalLayout.addWidget(self.Submit_Details3)
        self.formLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 180, 471, 251))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 20, 0, 0)
        self.formLayout_2.setHorizontalSpacing(0)
        self.formLayout_2.setVerticalSpacing(75)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.Drive_Card_Name = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.Drive_Card_Name.setObjectName("Drive_Card_Name")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.Drive_Card_Name)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.Driver_card_account_number = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.Driver_card_account_number.setObjectName("Driver_card_account_number")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.Driver_card_account_number)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Driver_Card_SortCode1 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.Driver_Card_SortCode1.setObjectName("Driver_Card_SortCode1")
        self.horizontalLayout.addWidget(self.Driver_Card_SortCode1)
        self.Driver_Card_SortCode2 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.Driver_Card_SortCode2.setObjectName("Driver_Card_SortCode2")
        self.horizontalLayout.addWidget(self.Driver_Card_SortCode2)
        self.Driver_Card_SortCode3 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.Driver_Card_SortCode3.setObjectName("Driver_Card_SortCode3")
        self.horizontalLayout.addWidget(self.Driver_Card_SortCode3)
        self.formLayout_2.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(110, 40, 271, 141))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("PIX/cardz.png"))
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Submit_Details3.setText(_translate("Form", "Submit"))
        self.label_2.setText(_translate("Form", "Name:"))
        self.label_4.setText(_translate("Form", "Account Number:"))
        self.label_5.setText(_translate("Form", "Sort Code:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form6()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
