# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'User_Registration_Error.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(500, 500))
        Form.setMaximumSize(QtCore.QSize(500, 500))
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 481, 431))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.User_First_Name_Error = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.User_First_Name_Error.setText("")
        self.User_First_Name_Error.setObjectName("User_First_Name_Error")
        self.verticalLayout.addWidget(self.User_First_Name_Error)
        self.User_Last_Name_Code = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.User_Last_Name_Code.setText("")
        self.User_Last_Name_Code.setObjectName("User_Last_Name_Code")
        self.verticalLayout.addWidget(self.User_Last_Name_Code)
        self.User_Email_Error = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.User_Email_Error.setText("")
        self.User_Email_Error.setObjectName("User_Email_Error")
        self.verticalLayout.addWidget(self.User_Email_Error)
        self.User_Contact_Number = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.User_Contact_Number.setText("")
        self.User_Contact_Number.setObjectName("User_Contact_Number")
        self.verticalLayout.addWidget(self.User_Contact_Number)
        self.User_Password_Error = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.User_Password_Error.setText("")
        self.User_Password_Error.setObjectName("User_Password_Error")
        self.verticalLayout.addWidget(self.User_Password_Error)
        self.User_Payment_Error = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.User_Payment_Error.setText("")
        self.User_Payment_Error.setObjectName("User_Payment_Error")
        self.verticalLayout.addWidget(self.User_Payment_Error)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 460, 481, 31))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.CloseBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CloseBtn.sizePolicy().hasHeightForWidth())
        self.CloseBtn.setSizePolicy(sizePolicy)
        self.CloseBtn.setObjectName("CloseBtn")
        self.verticalLayout_2.addWidget(self.CloseBtn)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.CloseBtn.setText(_translate("Form", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
